# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KAYN1QCgKV-1h8mKqZxGwIQXB97rss9A

Лабораторная работа 1

Самостоятельные задания

1.
"""

a = 5
b = int(input())
print(a*b)

"""2."""

a = int(input())
b = int(input())
print((a+b)**2)

"""3."""

a = 15
b = 10
c = int(input())
if c==0:
    print("Ошибка! Делитель равен нулю")
print((a+b)/c)

"""4."""

a = int(input())
b = int(input())
print((a+b)**2)

"""5."""

import math
a = int(input())
b = int(input())
c = int(input())
p = a+b+c
print(f"P = {p} \n S = {math.sqrt((p/2)*(p/2-a)*(p/2-b)*(p/2-c))}")

"""6."""

a = int(input())
b = int(input())
print(((a**3+14)/5)*b)

"""7."""

a = int(input())
n = int(input())
print((a**2)//n)

"""8."""

a = float(input())
b = float(input())
print(a//b)
a2 = int(input())
b2 = int(input())
print(a*b)
a3 = int(input())
b3 = int(input())
print(a%b)

"""Задания повышенной сложности"""

s = int(input())
days = s//(60*60*24)
s -= days*(60*60*24)
hours = s//(60*60)
s -= hours*(60*60)
mins = s//60
s -= mins*60
print(f"{days} дней, {hours} часов, {mins} минут, {s} секунд")

n = int(input())
print(n + n**2 + n**3)