# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aCHUkDXC9peug98wTSLoH90mqZzl-rTK

Лабораторная работа №3

1
"""

month = [
    "Январь",
    "Февраль",
    "Март",
    "Апрель",
    "Май",
    "Июнь",
    "Июль",
    "Август",
    "Сентябрь",
    "Октябрь",
    "Ноябрь",
    "Декабрь"
]
n = int(input())

print(month[n-1])

"""2"""

n = int(input())
if n%2==0:
    print("Чёт")
else:
    print("Нечёт")

"""3"""

n = int(input())
if n>40:
    print("Stonks")
else:
    print("Not stonks")

"""4"""

def is_year_leap(year):
    if year%4==0:
        return True
    else:
        return False
print(is_year_leap(int(input())))

"""5"""

def is_prime(n):
    p = True
    for i in range(2, n):
        if n%i==0:
            p = False
    return p
print(is_prime(int(input())))

"""6"""

import math
print("a = ")
a = float(input())
print("b = ")
b = float(input())
#В условии, вероятно, была ошибка, потому что минимальная точка промежутка была (-138/2)^1.3, т. е. являлось комплексным числом
if (a/b==3.6) or ((b >= -138/(2**1.3)) and (b<= math.fabs((-69/(28**5.1))*4))):
    a, b = b, a
print(f"a = {a} \n b = {b}")

"""7"""

nums = []
hon = 0
neg = 0
inl = 0
uniq = True
for i in range(5):
    n = int(input())
    if n % 2==0:
        hon+=1
    if n < 0:
        neg += 1
    if (n >= -256) and (n <= 1024):
        inl += 1
    if n in nums:
        uniq = False
    nums.append(n)
print(f"{nums}\nЧётных: {hon}\nОтрицательных: {neg}\nЛежащих на отрезке [-256; 1024]: {inl}\n")
if uniq:
    print("Все числа уникальны")
else:
    print("Не все числа уникальны")

"""Задание повышенной сложности"""

#Просто разделить число на 4 или опять не то что-то с условием?
n = float(input())
ans = n/4
print(f"{n}/4={ans}")
while not (ans/1==ans//1):
    ans *= 10
hon = ans%2==0
if hon:
    print("Ответ чётный")
else:
    print("Ответ нечётный")